#!/usr/bin/env sh

exitWithErrorMsg() {
  if [ "" = "$1" ]; then
    echo "Unknown Error"
    exit 101
  fi
  echo "$*"
  exit "$1"
} >&2

SCRIPT_FULL_PATH="$(realpath "$0")"

cd "$(dirname "$SCRIPT_FULL_PATH")" || exitWithErrorMsg 102 "dirname of $SCRIPT_FULL_PATH not found"

. app_sh_lib/app_runtime_lib.sh

lookupDevPlace "$SCRIPT_FULL_PATH"

echo  "SCRIPT_FULL_PATH          $SCRIPT_FULL_PATH"
echo  "PLACE_OF_SCRIPT_FULL_PATH $PLACE_OF_SCRIPT_FULL_PATH"
echo  "SCRIPT_NAME               $SCRIPT_NAME"
echo  "DEV_PLACE_ROOT_FULL_PATH  $DEV_PLACE_ROOT_FULL_PATH"
echo  "DEV_PLACE_NAME            $DEV_PLACE_NAME"
