#!/usr/bin/env sh

exitWithErrorMsg() {
  if [ "" = "$1" ]; then
    echo "Unknown Error"
    exit 101
  fi
  echo "$*"
  exit "$1"
} >&2

SCRIPT_FULL_PATH="$(realpath "$0")"

cd "$(dirname "$SCRIPT_FULL_PATH")" || exitWithErrorMsg 102 "dirname of $SCRIPT_FULL_PATH not found"

. app_sh_lib/app_runtime_lib.sh

ensure_app_by_script_place "$SCRIPT_FULL_PATH"

cat <<EOF >"$APP_BY_SCRIPT__DIR/apps_list.txt"
//$(realpath "$PLACE_OF_SCRIPT_FULL_PATH/..")
$(realpath "$PLACE_OF_SCRIPT_FULL_PATH/../plus/app0")
$(realpath "$PLACE_OF_SCRIPT_FULL_PATH/../plus/app1")
$(realpath "$PLACE_OF_SCRIPT_FULL_PATH/../plus/app2")
$(realpath "$PLACE_OF_SCRIPT_FULL_PATH/../plus/app3")
EOF

scriptTemplateName="$( basename "$PLACE_OF_SCRIPT_FULL_PATH" )"
tail --lines=+10 "$PLACE_OF_SCRIPT_FULL_PATH/../plus/scriptTemplate/kt/${scriptTemplateName}.kt" >"$APP_BY_SCRIPT_TOOL_FILE"

#echo "$TOOL_ONE_RUN_CMD" $TOOL_ONE_RUN_DEFAULT_ARGS "$@"
# shellcheck disable=SC2086
"$TOOL_ONE_RUN_CMD" $TOOL_ONE_RUN_DEFAULT_ARGS "$@"
