#!/usr/bin/env sh
#
#
#
#
#
#
#
#
#

###

CMD='nvim --clean -l'
SCRIPT="$(dirname "$(realpath "$0")")"/lua/app.lua

$CMD "$SCRIPT" link_out_place

RESULT_CMD=$($CMD "$SCRIPT" echoAppsByScriptStartCmd '..')

echo "RESULT_CMD: })>$RESULT_CMD<({"
sh -c "$RESULT_CMD $*"
