#!/usr/bin/env sh
#
#
#
#
#
#
#
#
#

###

THIS_SCRIPT_FULL_PATH="$(realpath "$0")"
THIS_SCRIPT_NAME="$(basename "$THIS_SCRIPT_FULL_PATH")"

CMD='nvim --clean -l'
SCRIPT="$(dirname "$(realpath "$0")")"/lua/app.lua

$CMD "$SCRIPT" link_out_place

RESULT_CMD=$($CMD "$SCRIPT" echoAppsByScriptStartCmd "$THIS_SCRIPT_NAME" '..')

echo "RESULT_CMD: })>$RESULT_CMD<({"
sh -c "$RESULT_CMD $*"
