#!/usr/bin/env sh
#
#
#
#
#
#
#
#
#

###

CMD='nvim --clean -l'
SCRIPT="$(dirname "$(realpath "$0")")"/lua/app.lua

RESULT_CMD=$($CMD "$SCRIPT" open_in_ide2)

echo "RESULT_CMD: })>$RESULT_CMD<({" >&2
sh -c "$RESULT_CMD $*" &
